package com.kstorozh.dataimpl

enum class ErrorStatus {
    INVALID_PASSWORD,
    INVALID_LOGIN,
    UNAUTHORIZED,
    UNEXPECTED_ERROR,
    CAN_NOT_INI_DEVICE,
    CAN_NOT_UPDATE_DEVICE,
    CAN_NOT_BOOK_DEVICE,
    CAN_NOT_RETURN_DEVICE,
    CAN_NOT_GET_USERS,
    CAN_NOT_REMIND_PIN,
    CAN_NOT_GET_BOOKING
}